imports:
- path: sas-viya-template.jinja

resources:
- name: sas-viya
  type: sas-viya-template.jinja
  properties:
    AdminIngressLocation: 149.173.0.0/16 
    zone: <ZONE>
    ssh-key: <SSH PUBLIC KEY>
    